version: '3.7'

services:

  eventstore:
    container_name: eventstore
    image: eventstore/eventstore:release-5.0.8
    ports:
      - '2113:2113'
      - '1113:1113'
    environment:
      EVENTSTORE_DEV: 'true'
      EVENTSTORE_CLUSTER_SIZE: 1
      EVENTSTORE_EXT_TCP_PORT: 1113
      EVENTSTORE_EXT_HTTP_PORT: 2113
      EVENTSTORE_ENABLE_EXTERNAL_TCP: 'true'
      EVENTSTORE_DISABLE_EXTERNAL_TCP_TLS: 'true'
      EVENTSTORE_RUN_PROJECTIONS: all
      EVENTSTORE_START_STANDARD_PROJECTIONS: "true"
      EVENTSTORE_DISABLE_INTERNAL_TCP_TLS: 'true'

networks:
  default:
    name: test-network

